version: '3.7'

services:
  servo:
    build:
      context: .
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    environment:
      - OPSANI_OPTIMIZER=${OPSANI_OPTIMIZER:?Opsani Optimizer must be configured}
      - OPSANI_TOKEN_FILE=${OPSANI_TOKEN_FILE:-/var/run/secrets/opsani.com/optimizer.token}
      - OPSANI_CONFIG_FILE=${OPSANI_CONFIG_FILE:-/servo/servo.yaml}
    volumes:
      - ./secrets:${OPSANI_TOKEN_FILE}
      - ./servo.yaml:${OPSANI_CONFIG_FILE}      
    command: --auth-token /run/secrets/optune_auth_token --account ${OPTUNE_ACCOUNT:?The Optune Account Name must be configured.} ${OPTUNE_APP_ID:?The Optune App ID must be configured.}
