[tool.poetry]
name = "servo"
version = "0.1.0"
description = "Opsani Servo: The Next Generation"
authors = ["Blake Watters <blake@opsani.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.5.1"
loguru = "^0.5.1"
httpx = "^0.13.3"
typer = "^0.2.1"
python-dotenv = "^0.13.0"
semver = "^2.10.1"
pyaml = "^20.4.0"
durationpy = "^0.5"
tabulate = "^0.8.7"
pygments = "^2.6.1"
devtools = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-asyncio = "^0.12.0"
pytest-cov = "^2.10.0"
isort = "^4.3.21"
autoflake = "^1.3.1"
flake8-fixme = "^1.1.1"
mypy = "^0.780"
wemake-python-styleguide = "^0.14.0"
devtools = "^0.5.1"
ipython = "^7.15.0"
black = "^19.10b0"

[tool.poetry.scripts]
servo = "servo.cli:main"

# TODO: Example entry point for testing plugins
[tool.poetry.plugins."servo.connectors"]
"connector-test" = "servo.testing:TestConnector"
"vegeta" = "connectors.vegeta.vegeta:VegetaConnector"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
