name: Quick Start
on: [push, pull_request]

jobs:
  quick_start:
    name: Pyenv Quick Start
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.5
          - 3.8.6
          - 3.9.0

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        versions: 3.8.5, 3.8.6, 3.9.0
        command: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          pyenv install
          poetry env use `cat .python-version`
          poetry install
    - name: Run tests
      run: pytest .
